[project]
name = "pt-jax"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "jax>=0.5.3",
    "jaxlib>=0.5.3",
    "scipy>=1.15.2",
]
